# Generated by Django 5.1.2 on 2024-10-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_remove_expense_amount_remove_expense_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
